version: '3'
services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=bitbnb
      # - MONGO_INITDB_ROOT_PASSWORD=bitpassw0rdbnb
    volumes:
      - mongo:/data/db
volumes:
  mongo:
    name: mongo