from base.Wallet import Wallet

if __name__ == '__main__':   
    # generated by Bitbnb app when user clicks "reserve"
    serial_script = '76a91438e36fc755a30589652fc01830de28bcd58178bd8763ac670313c024b17576a914ad86bcc9e99b6888c9e99019b74caece625fe98c88ac68'
    total_rent_cost = 2000

    # from renter's wallet
    wallet = Wallet('alice_wallet', 'jag2k2', 'jeff1229', '169.254.122.179', 18332)
    tx_id = wallet.book_reservation(total_rent_cost, serial_script)
    print(tx_id)