from lib.rpc import RpcSocket
from Bitbnb.Tx_Factory import Tx_Factory
from Bitbnb.RedeemScript import RedeemScript

if __name__ == '__main__':   
    # generated by Bitbnb app when user clicks "reserve"
    serial_script = '76a91438e36fc755a30589652fc01830de28bcd58178bd8763ac670313c024b17576a914ad86bcc9e99b6888c9e99019b74caece625fe98c88ac68'
    rent_price = 2000

    # from renter's wallet
    from_rpc = RpcSocket({'wallet': 'alice_wallet'})
    all_txins = from_rpc.get_all_utxos(testnet=True)    # find list of utxos with sufficient funds
    all_amount = from_rpc.get_total_unspent_sats()      # get total amount in those utxos
    fee = 500                                           # bitcoin miners fees
    change_amount = all_amount - rent_price - fee       # calculate how much is returning to renter's wallet
    tx_out_change = from_rpc.get_txout(change_amount)   # generate p2pkh output for change

    # executed by Bitbnb app
    redeem_script = RedeemScript.make_from_serial(serial_script)                                    # build redeem_script from serial string
    transaction = Tx_Factory.make_funding(redeem_script, rent_price, all_txins, tx_out_change)      # construct funding transaction
    
    #signed and sent by renter's wallet
    transaction.sign(from_rpc, testnet=True)           # sign funding transaction
    print(transaction)
    print(transaction.serialize().hex())
    tx_id = from_rpc.send_transaction(transaction)