from lib.rpc import RpcSocket
from shared.Tx import Tx, TxOut
from shared.Script import Script
from shared.Utility import hash160
from Bitbnb.Tx_Factory import Tx_Factory
from Bitbnb.RedeemScript import RedeemScript

if __name__ == '__main__':   

    # generated by Bitbnb app when user click's "reserve"
    serial_script = '76a9145850a5cfd6254cd20b00493a1fd063c166043adc8763ac67034abd24b17576a914a2ec72b722b3840c7f74a38a1a7482f91e5852fa88ac68'
    rent_price = 2000

    # from renter's wallet
    from_rpc = RpcSocket({'wallet': 'alice_wallet'})
    all_txins = from_rpc.get_all_utxos()                # find list of utxos with sufficient funds
    all_amount = from_rpc.get_total_unspent_sats()      # get total amount in those utxos
    fee = 500                                           # bitcoin miners fees
    change_amount = all_amount - rent_price - fee       # calculate how much is returning to renter's wallet
    tx_out_change = from_rpc.get_txout(change_amount)   # generate p2pkh output for change

    # executed by Bitbnb app
    redeem_script = RedeemScript.make_from_serial(serial_script)
    transaction = Tx_Factory.make_funding(redeem_script, rent_price, all_txins, tx_out_change)
    
    #signed and sent by renter's wallet
    transaction.sign(from_rpc)
    print(transaction)
    print(transaction.serialize().hex())
    tx_id = from_rpc.send_transaction(transaction)