from Bitbnb.Wallet import Wallet

if __name__ == '__main__':   
    # generated by Bitbnb app when user clicks "reserve"
    txid_with_p2wsh = 'be4d5d5a7900c3033c7caccbb0c1e486d3b0d258bd479b1651ae438e9c350d63'
    serial_script = '76a91438e36fc755a30589652fc01830de28bcd58178bd8763ac670313c024b17576a914ad86bcc9e99b6888c9e99019b74caece625fe98c88ac68'

    # from owner's wallet
    wallet = Wallet('bob_wallet')
    tx_id = wallet.finalize_reservation(txid_with_p2wsh, serial_script)
    print(tx_id)