from lib.rpc import RpcSocket
from shared.Tx import Tx, TxIn
from Bitbnb.Tx_Factory import Tx_Factory
from Bitbnb.RedeemScript import RedeemScript

if __name__ == '__main__':   
    # generated by Bitbnb app when user click's "reserve"
    txid_with_p2sh = '325e6f7922836078ac6afc61bce5457b06de365401b0594d5da3f27117081a51'
    serial_script = '76a9145850a5cfd6254cd20b00493a1fd063c166043adc8763ac67034abd24b17576a914a2ec72b722b3840c7f74a38a1a7482f91e5852fa88ac68'

    # from renter's wallet
    to_rpc = RpcSocket({'wallet': 'alice_wallet'})
    utxo_to_redeem = to_rpc.lookup_transaction(txid_with_p2sh).tx_outs[0]
    utxo_amount = utxo_to_redeem.amount
    bitcoin_miner_fee = 500
    redeem_amount = utxo_amount - bitcoin_miner_fee
    refund_tx_out = to_rpc.get_txout(redeem_amount)

    # executed by Bitbnb app
    redeem_script = RedeemScript.make_from_serial(serial_script) 
    transaction = Tx_Factory.make_refund(txid_with_p2sh, refund_tx_out)

    # executed by renter's wallet
    input_index_to_sign = 0
    transaction.signP2SH(to_rpc, input_index_to_sign, redeem_script, testnet=True)
    
    print(transaction)
    print(transaction.serialize().hex())
    tx_id = to_rpc.send_transaction(transaction)
