from Bitbnb.Wallet import Wallet

if __name__ == '__main__':   
    # generated by Bitbnb app when user clicks "reserve"
    txid_with_p2wsh = '38aab8d00b0d7b1912ea9a76654a326db0fc81a6de15e2818c94750ae04ae5b7'
    serial_script = '76a91438e36fc755a30589652fc01830de28bcd58178bd8763ac670313c024b17576a914ad86bcc9e99b6888c9e99019b74caece625fe98c88ac68'

    # from renter's wallet
    wallet = Wallet('alice_wallet')
    tx_id = wallet.cancel_reservation(txid_with_p2wsh, serial_script)
    print(tx_id)
